# setting the prefix to ctrl+n
set -g prefix C-n
# Free the original prefix ctrl+b
unbind C-b
# Setting a small delay between prefix and command
set -g escape-time 1
# Setting the starting window to start and 1 instead of 0
set -g base-index 1
# Setting the base of panes to 1 instead of 0
setw -g pane-base-index 1

# Reload the file with Prefix r	
bind r source-file ~/.tmux.conf	\; display "Conf Reloaded!"

# Ensure we send Ctlr+n to other application which may need it
bind C-n send-prefix
# Spitting windows with - and |
bind | split-window -h
bind - split-window -v

# moving between panes with Prefix h,j,k,l 
bind h select-pane -L	
bind j select-pane -D 
bind k select-pane -U	
bind l select-pane -R

# Quick	window	selection	
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Resizing panes incrementaly in all directions
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5	
bind -r K resize-pane -U 5	
bind -r L resize-pane -R 5 

# Mouse support - set to off
set -g mouse off

# Set the visual mode to 256color Mode
set -g default-terminal "screen-256color"






