map bf shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/files 
map bd shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/directories 
map bw shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/bookmarks 
map cfa shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc 
map cfz shell $EDITOR $ZDOTDIR/.zshrc 
map cfv shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/init.vim 
map cft shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/.tmux.conf 
map cfm shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/mutt/muttrc 
map cfx shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources 
map cfu shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls 
map cfn shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/config 
map cfmb shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/ncmpcpp/bindings 
map cfmc shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/ncmpcpp/config 
map cfk shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/sxhkd/sxhkdrc 
map cfi shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/i3/config 
map cfb shell $EDITOR ${XDG_CONFIG_HOME:-$HOME/.config}/i3blocks/config 
