format = '$directory$time$shell$character'

[package]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[nodejs]
disabled = true

[golang]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true
